### PR TITLE
Vendor our dependency on the Nomad API client

### LINKED ISSUE #25: Missing Nomad dependencies in master
The following is output from attempting to run `dep ensure` within [master](https://github.com/joyent/triton-service-groups/commit/9a424949c7dab4f1c3bb81ac03a5e56dc6f74b0e) in order to resolve dependency issues in #23.

```
$ dep status
Lock inputs-digest mismatch due to the following packages missing from the lock:

PROJECT                     MISSING PACKAGES
github.com/hashicorp/nomad  [github.com/hashicorp/nomad/api github.com/hashicorp/nomad/jobspec]

This happens when a new import is added. Run `dep ensure` to install the missing packages.
input-digest mismatch
```

Running `dep ensure` breaks the existing build (for me).

```
$ go run main.go
# github.com/joyent/triton-service-groups/vendor/github.com/hashicorp/nomad/nomad/structs
vendor/github.com/hashicorp/nomad/nomad/structs/structs.generated.go:125:6: r.EncodeArrayStart undefined (type "github.com/joyent/triton-service-groups/vendor/github.com/ugorji/go/codec".genHelperEncDriver has no field or method EncodeArrayStart)
vendor/github.com/hashicorp/nomad/nomad/structs/structs.generated.go:133:6: r.EncodeMapStart undefined (type "github.com/joyent/triton-service-groups/vendor/github.com/ugorji/go/codec".genHelperEncDriver has no field or method EncodeMapStart)
vendor/github.com/hashicorp/nomad/nomad/structs/structs.generated.go:137:6: z.EncSendContainerState undefined (type "github.com/joyent/triton-service-groups/vendor/github.com/ugorji/go/codec".genHelperEncoder has no field or method EncSendContainerState)
vendor/github.com/hashicorp/nomad/nomad/structs/structs.generated.go:145:6: z.EncSendContainerState undefined (type "github.com/joyent/triton-service-groups/vendor/github.com/ugorji/go/codec".genHelperEncoder has no field or method EncSendContainerState)
vendor/github.com/hashicorp/nomad/nomad/structs/structs.generated.go:147:6: z.EncSendContainerState undefined (type "github.com/joyent/triton-service-groups/vendor/github.com/ugorji/go/codec".genHelperEncoder has no field or method EncSendContainerState)
vendor/github.com/hashicorp/nomad/nomad/structs/structs.generated.go:156:6: z.EncSendContainerState undefined (type "github.com/joyent/triton-service-groups/vendor/github.com/ugorji/go/codec".genHelperEncoder has no field or method EncSendContainerState)
vendor/github.com/hashicorp/nomad/nomad/structs/structs.generated.go:164:6: z.EncSendContainerState undefined (type "github.com/joyent/triton-service-groups/vendor/github.com/ugorji/go/codec".genHelperEncoder has no field or method EncSendContainerState)
vendor/github.com/hashicorp/nomad/nomad/structs/structs.generated.go:166:6: z.EncSendContainerState undefined (type "github.com/joyent/triton-service-groups/vendor/github.com/ugorji/go/codec".genHelperEncoder has no field or method EncSendContainerState)
vendor/github.com/hashicorp/nomad/nomad/structs/structs.generated.go:175:6: z.EncSendContainerState undefined (type "github.com/joyent/triton-service-groups/vendor/github.com/ugorji/go/codec".genHelperEncoder has no field or method EncSendContainerState)
vendor/github.com/hashicorp/nomad/nomad/structs/structs.generated.go:177:6: z.EncSendContainerState undefined (type "github.com/joyent/triton-service-groups/vendor/github.com/ugorji/go/codec".genHelperEncoder has no field or method EncSendContainerState)
vendor/github.com/hashicorp/nomad/nomad/structs/structs.generated.go:177:6: too many errors
```

@stack72 I'm not sure what version of Nomad you were running. I could make a wild guess but it would be good to know what version or SHA you've used recently.

### PR DESCRIPTION
**Pull request by cheapRoc**
This commit adds our dependency on Nomad to the vendor directory. I've also included a README.md which outlines the environment variables used in this version of the app, for demo purposes.

So far I believe this fixes #25 but it would be nice to have a confirmation. If so, I'd like to get this merged and rebased into #23.

### CODE REVIEW

**Comment by stack72** [comment]
We need to vendor Nomad 0.7.1 0 I opened #27 that does this before I saw this PR

I don't mind which you merge

**Comment by cheapRoc** [comment]
When I tried 0.7.1 it was giving me the errors I listed in #25. But I’d rather your PR if it doesn’t do the same so I’ll check that out when I’m back.

**Comment by cheapRoc** [comment]
Really don't want master so I'm punting this PR.

**Comment by cheapRoc** [comment]
I've reset and force pushed master off #27 and replacing with this.

**Pull request merged**
