### PR TITLE
Build TSG as a configurable/deployable binary

### LINKED ISSUE #6: Introduce context package
We need to generate a new `context.Context` for each incoming request (session) then feed that into every backend I/O function like database or CloudAPI calls. This should remove all the `context.TODO` that are stubbed out for the time being.

Also, test that a HTTP request fails gracefully at any point. I believe implementing a single context will provide us this.

### PR DESCRIPTION
**Pull request by cheapRoc**
This PR adds the following much needed production qualities to the project.

- Introduces logging across the project with database adapter and HTTP using the same logger.
- Build an easily deployable binary tagged by git SHA at `buildtime`.
- Provide configuration of database, and logging, as well as Nomad server config in the future.
- Environment variable overrides for default configuration.
- Handle process signals and gracefully drain HTTP connections.
- Fixes #6 by introducing the `context` package for app and HTTP request lifecycles.
- Add `gops(1)` and `pprof` for debugging and observability.

In various forms, these behaviors are shared among other Joyent-Go projects and we should follow similar patterns. Hopefully these are welcome additions.

### CODE REVIEW

**Comment by cheapRoc** [comment]
Note: I have one `templates_v1.List` handler ported over and will continue with the remaining (after some grub).

**Comment by cheapRoc** [comment]
Another reminder, I need to `dep ensure` and include all dependencies.

**Comment by cheapRoc** [comment]
All endpoints should be converted over, unless there's an orchestration function or two that I've goofed.

New dependencies need to be vendored but I was receiving an issue with our dependency on the Nomad API. Not sure what's up there so I've left the new libs out for now.

**Comment by cheapRoc** [comment]
Also, here's a link to the new [README.md](https://github.com/cheapRoc/triton-service-groups/blob/c082c53bcafe6c8f31ea203d0d531769bf8263b2/README.md).

**Comment by cheapRoc** [comment]
Forgot about tests, updating them now.

**Comment by cheapRoc** [comment]
Tests now pass given recent ID/URL changes in master. Also, I didn't introduce any of the enhancements from #16 given the comfort level for the amount of changes in this PR. They can be brought in after.

**Comment by stack72** [comment]
@cheapRoc you can merge this when you want

**Comment by cheapRoc** [comment]
@stack72 what about the dependencies?

**Comment by stack72** [comment]
@cheapRoc that's currently broken in master so it can be taken as a followup

**Comment by cheapRoc** [comment]
@stack72 Thanks, before I left for lunch it looked like I got a successful `dep ensure` and build by applying #26.

**Comment by cheapRoc** [comment]
Ok, all remaining dependencies have been resolved to a clean `make build`. I'll merge in a little bit.

**Pull request merged**
