### PR TITLE
dependency - add jackc/pgx

### PR DESCRIPTION
**Pull request by stack72**
Adding the database dependency to the system. The addition to the db package
is required until we start using it, otherwise `dep ensure` will remove from
the vendor folder

//cc @cheapRoc / @sean-

### CODE REVIEW

**Comment by cheapRoc** [comment]
👍

**Comment by cheapRoc** [comment]
Might want to stick this simple `docker-compose.yml` in there too.

```yaml
version: '2.1'

services:

  db:
    image: cockroachdb/cockroach:v1.1.4
    restart: always
    mem_limit: 256m
    ports:
      - "26257:26257"
      - "8080:8080"
    network_mode: bridge
    command: start --insecure
```

**Comment by stack72** [comment]
@cheapRoc TBH, I have NFC how to use this library yet :) I promise we will add something when we get it working - this is more for a reminder than anything atm

**Comment by cheapRoc** [comment]
This stuff has to start somewhere.

**Comment by sean-** [comment]
Let me know if someone has a question about how to do this and I can jump over to jump into `pgx`.  I'm assuming that's the library you're talking about @stack72 ?

**Pull request merged**
